# Generated by Django 4.0.6 on 2022-09-04 15:11

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to=dashboard.models.only_filename)),
                ('document_raw', models.FileField(default='Some String', upload_to=dashboard.models.only_filename)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('calendar_week', models.CharField(max_length=200, null=True)),
                ('raw_entries', models.IntegerField(null=True)),
                ('clean_entries', models.IntegerField(null=True)),
                ('city', models.CharField(max_length=200, null=True)),
                ('avg_price_sqrm', models.IntegerField(default=0, null=True)),
                ('avg_size', models.IntegerField(default=0, null=True)),
                ('avg_year', models.IntegerField(default=0, null=True)),
                ('highest_price', models.IntegerField(default=0, null=True)),
                ('highest_price_link', models.URLField(default='Some String')),
                ('highest_price_sqrm', models.IntegerField(default=0, null=True)),
                ('highest_price_sqrm_link', models.URLField(default='Some String')),
                ('lowest_price', models.IntegerField(default=0, null=True)),
                ('lowest_price_link', models.URLField(default='Some String')),
                ('lowest_price_sqrm', models.IntegerField(default=0, null=True)),
                ('lowest_price_sqrm_link', models.URLField(default='Some String')),
            ],
        ),
    ]
