# Generated by Django 4.0.6 on 2022-12-11 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rents'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='avg_price',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='rents',
            name='avg_price',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
