# Generated by Django 4.0.6 on 2022-12-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_document_avg_price_rents_avg_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='avg_price',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='avg_price_sqrm',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='avg_size',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='highest_price_sqrm',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='lowest_price_sqrm',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rents',
            name='avg_price',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rents',
            name='avg_price_sqrm',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rents',
            name='avg_size',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rents',
            name='highest_price_sqrm',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rents',
            name='lowest_price_sqrm',
            field=models.FloatField(default=0, null=True),
        ),
    ]
