# Generated by Django 4.0.6 on 2023-01-20 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_document_year_calendar_week_rents_year_calendar_week_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rents',
            name='avg_price_sqrm_decimal',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='rents',
            name='highest_price_sqrm_decimal',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='rents',
            name='lowest_price_sqrm_decimal',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
