# Generated by Django 4.0.6 on 2023-01-27 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_rents_avg_price_sqrm_decimal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='year_calendar_month',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rents',
            name='year_calendar_month',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
